package uk.co.scattercode.drools.util

import uk.co.scattercode.drools.util.testfacts.Customer
import uk.co.scattercode.drools.util.testfacts.Product


rule "Decrement count"
when
	$product : Product(count > 10)
then
	$product.setCount($product.getCount() - 1);
	update($product)
end


rule "Greet customer"
when
	$customer : Customer(!greeted)
then
	$customer.setGreeted(true);
	update($customer);
end