package sctrcd.iban

import uk.co.scattercode.iban.facts.*

global java.util.List countryList;

rule "Must begin with a country ISO code."
when
    $req: IbanValidationRequest($iban:iban, $country:iban.substring(0, 2))
    not Country(isoCode == $country)
then
    // Create a rejection annotation.
    $req.addAnnotation(new IbanValidationAnnotation(
           $iban, 
           false, 
           "An IBAN must begin with a 2-character country code."));
    update($req);
end
